[package]
name = "tictactoe"
version = "0.1.0"
edition = "2021"

[dependencies]
pc-keyboard = "0.5.0"
bootloader = "0.9.8"
spin = "0.5.2"

kernel = { path = "../kernel" }

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
